name: bansi_expense_tracker
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  hive: ^2.2.3
  injectable: ^1.5.3
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.7.0
  logger: ^1.1.0
  retrofit: ^3.3.1
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.4
  json_serializable: ^6.5.0
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: NotoSanLao
      fonts:
        - asset: assets/fonts/NotoSansLao-Regular.ttf
        - asset: assets/fonts/NotoSansLao-Bold.ttf
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
